const { createRequire } = require('node:module');
const frontendRequire = createRequire(require('node:path').resolve('frontend/package.json'));
const { chromium } = frontendRequire('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PW_EXE||undefined,channel:process.env.PW_EXE?undefined:(process.env.MIZAN_BROWSER||'chrome')});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();
 const failures=[];
 page.on('pageerror',e=>failures.push(e.message));
 const root=process.env.MIZAN_TEST_URL||'http://127.0.0.1:8001';
 const out=path.resolve('work/browser');fs.mkdirSync(out,{recursive:true});
 const external=[];
 page.on('request',req=>{if(!req.url().startsWith(root)&&!req.url().startsWith('data:'))external.push(req.url())});
 await page.goto(root);
 await page.getByRole('button',{name:'Enter workspace'}).click();
 await page.getByRole('heading',{name:/Every hour of the week/}).waitFor();
 // Spec §13.11: Arabic and English show identical verified facts (every number on the overview, in order).
 const facts=async()=>{await page.waitForTimeout(1200);return page.evaluate(()=>[...document.querySelectorAll('.ov-big, .ov-stat strong, .ov-label .grade-word, .ov-facts strong, .cohort-chart .bar-row strong')].map(e=>e.innerText).join(' ').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).match(/\d[\d,.]*/g))};
 const factsEn=await facts();
 await page.screenshot({path:path.join(out,'overview-en.png'),fullPage:true});
 await page.getByRole('button',{name:'العربية',exact:true}).click();
 await page.getByRole('heading',{name:/كل ساعة في الأسبوع/}).waitFor();
 assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
 assert.ok(factsEn&&factsEn.length>10,'overview facts found');
 assert.deepEqual(await facts(),factsEn,'Arabic and English overview facts differ');
 await page.screenshot({path:path.join(out,'overview-ar.png'),fullPage:true});
 await page.getByRole('button',{name:'English',exact:true}).click();
 await page.getByRole('button',{name:'Semester lab',exact:true}).click();
 await page.getByRole('heading',{name:'Weekly timetable'}).waitFor();
 await page.screenshot({path:path.join(out,'semester.png'),fullPage:true});
 await page.getByRole('button',{name:'Place a section',exact:true}).click();
 await page.getByRole('button',{name:'Analyze slots',exact:true}).click();
 await page.locator('.placement-option').first().waitFor({timeout:30000});
 await page.getByRole('button',{name:'Propose',exact:true}).first().click();
 await page.getByRole('heading',{name:'Review the evidence'}).waitFor();
 await page.getByRole('button',{name:'Approve proposal',exact:true}).click();
 await page.locator('.proposal-card').first().click();
 await page.getByRole('button',{name:'Revalidate & publish locally',exact:true}).click();
 await page.getByText('Decision saved. The audit trail has been updated.').waitFor();
 console.log('PASS placement -> approval -> publication');
 await page.getByRole('button',{name:'Change requests',exact:true}).click();
 await page.getByLabel('Reason',{exact:true}).fill('Browser test: conflicting meeting');
 await page.getByRole('button',{name:'Evaluate change',exact:true}).click();
 await page.getByRole('heading',{name:'Feasible alternatives'}).waitFor({timeout:30000});
 await page.screenshot({path:path.join(out,'change-impact.png'),fullPage:true});
 await page.getByRole('button',{name:'Propose this',exact:true}).first().click();
 await page.getByRole('button',{name:'Approve proposal',exact:true}).waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 console.log('PASS conflict rejection -> valid alternative');
 await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption('shortfall');
 await page.getByRole('button',{name:'Workforce',exact:true}).click();
 await page.getByRole('button',{name:'Prepare requisition',exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'workforce.png'),fullPage:true});
 await page.getByRole('button',{name:'Prepare requisition',exact:true}).click();
 await page.getByRole('button',{name:'Recruitment',exact:true}).click();
 await page.getByRole('button',{name:'Authorize recruitment',exact:true}).first().waitFor();
 console.log('PASS shortage -> draft requisition');
 await page.getByRole('combobox',{name:'Scenario',exact:true}).selectOption('baseline');
 await page.getByRole('button',{name:'Recommendations',exact:false}).first().click();
 await page.getByRole('button',{name:'New optimization',exact:true}).click();
 await page.getByLabel('Solver time budget (seconds)',{exact:true}).fill('15');
 await page.getByRole('button',{name:'Run optimization',exact:true}).click();
 await page.getByRole('heading',{name:'Review the evidence'}).waitFor({timeout:60000});
 await page.screenshot({path:path.join(out,'optimization.png'),fullPage:true});
 await page.getByRole('button',{name:'Close',exact:true}).click();
 console.log('PASS full-scale optimization -> evidence review');
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile horizontal overflow');
 await page.getByRole('button',{name:/Mizan Administrator/}).click();
 await page.getByLabel('Demo role').selectOption('student');
 await page.getByRole('button',{name:'Enter workspace'}).click();
 await page.getByRole('heading',{name:'Your week, at a glance.'}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Workforce',exact:true}).count(),0);
 const result=await context.request.get(root+'/api/audit');assert.equal(result.status(),403);
 console.log('PASS student UI and backend authorization');
 assert.deepEqual(failures,[],'browser errors');
 assert.deepEqual(external,[],'runtime external network calls');
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed:true,pageErrors:failures,externalRequests:external,checkedAt:new Date().toISOString()},null,2));
 await browser.close();
 console.log('PASS all browser checks');
})().catch(e=>{console.error(e);process.exit(1)});
