"""Build the findings report for the coordinator experiment (PROTOCOL.md: paired differences + uncertainty)."""
from pathlib import Path
from math import comb
import json, random

ROOT = Path(__file__).resolve().parent
KEYS = ['valid', 'routing_correct', 'disposition_correct', 'pass', 'premature_finalization']
NAMES = {'valid': 'Valid bounded JSON', 'routing_correct': 'Next action correct', 'disposition_correct': 'Disposition correct',
         'pass': 'Combined pass', 'premature_finalization': 'Premature finalization (lower is better)'}


def load(label):
    p = ROOT / f'{label}_predictions.json'
    return {r['id']: r for r in json.loads(p.read_text(encoding='utf8'))} if p.exists() else None


def mcnemar(b, c):
    """Exact two-sided McNemar p-value for b vs c discordant pairs."""
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    return min(1.0, 2 * sum(comb(n, i) for i in range(k + 1)) / 2 ** n)


def bootstrap(diffs, reps=10000, seed=4101):
    rng = random.Random(seed); n = len(diffs)
    means = sorted(sum(diffs[rng.randrange(n)] for _ in range(n)) / n for _ in range(reps))
    return means[int(0.025 * reps)], means[int(0.975 * reps)]


def pct(x, n):
    return f'{x}/{n} ({100 * x / n:.1f}%)'


def main():
    base, tuned, gguf = load('pretrained_nf4'), load('finetuned_nf4'), load('gguf_baseline')
    if not base or not tuned:
        raise SystemExit('Missing pretrained_nf4 or finetuned_nf4 predictions; run train.py --evaluate-only first.')
    ids = sorted(set(base) & set(tuned)); n = len(ids)
    lines = ['# Coordinator fine-tuning experiment: findings', '',
             f'Frozen synthetic test set: {n} cases (balanced English/Arabic). Same official Qwen3-8B base in NF4, '
             'greedy decoding, 128-token cap, with vs. without the selected LoRA adapter.', '']
    tr = ROOT / 'training_result.json'
    if tr.exists():
        t = json.loads(tr.read_text(encoding='utf8'))
        lines += [f"Training: selected epoch {t['selected_epoch']} by validation loss {t['validation_loss']:.4f}; "
                  f"{t['optimizer_steps']} optimizer steps; {t['training_seconds'] / 60:.1f} min; "
                  f"peak GPU {t['peak_gpu_allocated_gib']} GiB; {t['trainable_parameters']:,} trainable parameters.", '']

    lines += ['## Primary comparison (paired)', '',
              '| Metric | Pretrained | Fine-tuned | Difference | 95% CI | Only fine-tuned / only pretrained | McNemar p |',
              '|---|---|---|---|---|---|---|']
    for k in KEYS:
        a = [int(base[i]['metrics'][k]) for i in ids]; b = [int(tuned[i]['metrics'][k]) for i in ids]
        diffs = [y - x for x, y in zip(a, b)]; lo, hi = bootstrap(diffs)
        only_t = sum(1 for x, y in zip(a, b) if y and not x); only_b = sum(1 for x, y in zip(a, b) if x and not y)
        lines.append(f'| {NAMES[k]} | {pct(sum(a), n)} | {pct(sum(b), n)} | {100 * sum(diffs) / n:+.1f} pts | '
                     f'{100 * lo:+.1f} to {100 * hi:+.1f} | {only_t} / {only_b} | {mcnemar(only_t, only_b):.3g} |')

    def breakdown(field, title):
        groups = sorted({base[i][field] for i in ids})
        out = ['', f'## Combined pass by {title}', '', f'| {title.capitalize()} | Pretrained | Fine-tuned |', '|---|---|---|']
        for g in groups:
            sel = [i for i in ids if base[i][field] == g]
            out.append(f"| {g} | {pct(sum(base[i]['metrics']['pass'] for i in sel), len(sel))} | "
                       f"{pct(sum(tuned[i]['metrics']['pass'] for i in sel), len(sel))} |")
        return out

    lines += breakdown('language', 'language') + breakdown('kind', 'case type')

    if gguf:
        g_ids = [i for i in ids if i in gguf]
        lines += ['', '## Secondary control: deployed GGUF model (different quantization/runtime, not paired with the above)', '',
                  '| Metric | Deployed GGUF |', '|---|---|']
        lines += [f"| {NAMES[k]} | {pct(sum(int(gguf[i]['metrics'][k]) for i in g_ids), len(g_ids))} |" for k in KEYS]
        leaks = sum(1 for i in g_ids if gguf[i].get('thinking_leaked'))
        if leaks:
            lines.append(f'\nNote: {leaks} GGUF responses contained a thinking block (stripped before grading).')

    lines += ['', '## Reading these results', '',
              '- This is a small synthetic benchmark generated by the same state generator as the training data. '
              'It measures generalization within the implemented coordinator workflow, not real-world ability.',
              '- A gain here does not prove deployment improvement and does not justify removing the production schema checks.',
              '- The adapter stays outside the live application until you explicitly approve it.']
    report = '\n'.join(lines) + '\n'
    (ROOT / 'coordinator_report.md').write_text(report, encoding='utf8')
    print(report)


if __name__ == '__main__':
    main()
